"""Catálogo de exames padrão de laboratório clínico brasileiro (base TUSS/AMB).

Formato: (code, name, section, material, method, unit, turnaround_hours, price)
"""
from decimal import Decimal

EXAMS: list[tuple[str, str, str, str, str | None, str | None, int, str]] = [
    # ==================== BIOQUÍMICA ====================
    ("GLIC",   "Glicose",                          "bioquimica", "soro",          "Enzimático hexoquinase",       "mg/dL",   4,  "12.00"),
    ("GLI_JJ", "Glicose pós-prandial",             "bioquimica", "soro",          "Enzimático hexoquinase",       "mg/dL",   4,  "12.00"),
    ("HBA1C",  "Hemoglobina glicada",              "bioquimica", "sangue EDTA",   "HPLC",                          "%",       24, "45.00"),
    ("UREIA",  "Ureia",                            "bioquimica", "soro",          "Urease UV",                     "mg/dL",   4,  "10.00"),
    ("CREA",   "Creatinina",                       "bioquimica", "soro",          "Jaffé cinético",                "mg/dL",   4,  "12.00"),
    ("URIC",   "Ácido úrico",                      "bioquimica", "soro",          "Uricase",                       "mg/dL",   4,  "12.00"),
    ("COL",    "Colesterol total",                 "bioquimica", "soro",          "Enzimático colorimétrico",      "mg/dL",   4,  "15.00"),
    ("HDL",    "Colesterol HDL",                   "bioquimica", "soro",          "Homogêneo direto",              "mg/dL",   4,  "20.00"),
    ("LDL",    "Colesterol LDL",                   "bioquimica", "soro",          "Cálculo Friedewald / direto",    "mg/dL",   4,  "20.00"),
    ("VLDL",   "Colesterol VLDL",                  "bioquimica", "soro",          "Cálculo",                       "mg/dL",   4,  "10.00"),
    ("TGL",    "Triglicerídeos",                   "bioquimica", "soro",          "Enzimático GPO-PAP",            "mg/dL",   4,  "15.00"),
    ("PROT",   "Proteínas totais",                 "bioquimica", "soro",          "Biureto",                       "g/dL",    4,  "10.00"),
    ("ALB",    "Albumina",                         "bioquimica", "soro",          "Verde bromocresol",             "g/dL",    4,  "10.00"),
    ("GLOB",   "Globulinas",                       "bioquimica", "soro",          "Cálculo",                       "g/dL",    4,  "8.00"),
    ("AST",    "TGO (AST)",                        "bioquimica", "soro",          "IFCC UV",                       "U/L",     4,  "12.00"),
    ("ALT",    "TGP (ALT)",                        "bioquimica", "soro",          "IFCC UV",                       "U/L",     4,  "12.00"),
    ("GGT",    "Gama GT",                          "bioquimica", "soro",          "IFCC cinético",                 "U/L",     4,  "15.00"),
    ("FA",     "Fosfatase alcalina",               "bioquimica", "soro",          "IFCC cinético",                 "U/L",     4,  "15.00"),
    ("BIL_T",  "Bilirrubina total",                "bioquimica", "soro",          "Diazo modificado",              "mg/dL",   4,  "12.00"),
    ("BIL_D",  "Bilirrubina direta",               "bioquimica", "soro",          "Diazo modificado",              "mg/dL",   4,  "12.00"),
    ("BIL_I",  "Bilirrubina indireta",             "bioquimica", "soro",          "Cálculo",                       "mg/dL",   4,  "8.00"),
    ("AMI",    "Amilase",                          "bioquimica", "soro",          "Enzimático colorimétrico",      "U/L",     4,  "20.00"),
    ("LIP",    "Lipase",                           "bioquimica", "soro",          "Enzimático colorimétrico",      "U/L",     4,  "22.00"),
    ("CK",     "CK total (CPK)",                   "bioquimica", "soro",          "NAC ativado",                   "U/L",     4,  "18.00"),
    ("CKMB",   "CK-MB",                            "bioquimica", "soro",          "Imunoinibição",                 "U/L",     4,  "25.00"),
    ("LDH",    "LDH (desidrogenase láctica)",      "bioquimica", "soro",          "IFCC UV",                       "U/L",     4,  "18.00"),
    ("Fe",     "Ferro sérico",                     "bioquimica", "soro",          "Ferrozina",                     "µg/dL",   4,  "18.00"),
    ("TIBC",   "Capacidade de ligação do ferro",   "bioquimica", "soro",          "Colorimétrico",                 "µg/dL",   6,  "20.00"),
    ("SAT_FE", "Saturação de transferrina",        "bioquimica", "soro",          "Cálculo",                       "%",       6,  "12.00"),
    ("CA",     "Cálcio total",                     "bioquimica", "soro",          "Arsenazo III",                  "mg/dL",   4,  "12.00"),
    ("CA_ION", "Cálcio iônico",                    "bioquimica", "soro",          "ISE",                           "mmol/L",  4,  "22.00"),
    ("P",      "Fósforo",                          "bioquimica", "soro",          "Molibdato UV",                  "mg/dL",   4,  "12.00"),
    ("MG",     "Magnésio",                         "bioquimica", "soro",          "Xylidyl blue",                  "mg/dL",   4,  "18.00"),
    ("Na",     "Sódio",                            "bioquimica", "soro",          "ISE",                           "mEq/L",   4,  "10.00"),
    ("K",      "Potássio",                         "bioquimica", "soro",          "ISE",                           "mEq/L",   4,  "10.00"),
    ("Cl",     "Cloreto",                          "bioquimica", "soro",          "ISE",                           "mEq/L",   4,  "10.00"),
    ("MICRO",  "Microalbuminúria",                 "bioquimica", "urina 24h",     "Imunoturbidimetria",            "mg/24h",  24, "35.00"),
    ("PROTU",  "Proteína urina 24h",               "bioquimica", "urina 24h",     "Vermelho de piragalol",         "mg/24h",  24, "20.00"),
    ("CREAU",  "Creatinina urinária",              "bioquimica", "urina",         "Jaffé",                         "mg/dL",   4,  "15.00"),
    ("CLCR",   "Clearance de creatinina",          "bioquimica", "sangue+urina",  "Cálculo",                       "mL/min",  4,  "25.00"),
    ("HB_GLI", "Frutosamina",                      "bioquimica", "soro",          "NBT",                           "µmol/L",  24, "38.00"),
    ("PCR",    "Proteína C reativa",               "bioquimica", "soro",          "Imunoturbidimetria",            "mg/L",    4,  "22.00"),
    ("PCRUS",  "PCR ultra-sensível",               "bioquimica", "soro",          "Nefelometria",                  "mg/L",    24, "45.00"),
    ("HAP",    "Haptoglobina",                     "bioquimica", "soro",          "Imunoturbidimetria",            "mg/dL",   24, "30.00"),
    ("TRANSF", "Transferrina",                     "bioquimica", "soro",          "Imunoturbidimetria",            "mg/dL",   24, "30.00"),

    # ==================== HEMATOLOGIA ====================
    ("HEMO",   "Hemograma completo",               "hematologia", "sangue EDTA",  "Impedância + Citometria fluxo",  None,      4,  "35.00"),
    ("PLAQ",   "Plaquetas (contagem)",             "hematologia", "sangue EDTA",  "Impedância",                    "/mm³",    4,  "15.00"),
    ("RETIC",  "Reticulócitos",                    "hematologia", "sangue EDTA",  "Citometria de fluxo",           "%",       6,  "22.00"),
    ("VHS",    "VHS (Velocidade de Hemossedimentação)", "hematologia", "sangue EDTA", "Westergren / Alifax",       "mm/h",    2,  "15.00"),
    ("COOMBS_D","Coombs direto",                   "hematologia", "sangue EDTA",  "Aglutinação em gel",            None,      6,  "25.00"),
    ("COOMBS_I","Coombs indireto",                 "hematologia", "soro",         "Aglutinação em gel",            None,      6,  "25.00"),
    ("TS",     "Tempo de sangramento",             "hematologia", "sangue capilar", "Duke / Ivy",                 "min",     2,  "10.00"),
    ("MIELO",  "Mielograma",                       "hematologia", "medula óssea", "Citológica",                    None,      72, "150.00"),
    ("HB_ELE", "Eletroforese de hemoglobina",      "hematologia", "sangue EDTA",  "Eletroforese alcalina",         None,      48, "60.00"),
    ("G6PD",   "G6PD (dosagem)",                   "hematologia", "sangue EDTA",  "Espectrofotometria",            "U/gHb",   48, "55.00"),

    # ==================== COAGULAÇÃO ====================
    ("TAP",    "TAP / Protrombina (INR)",          "coagulacao", "plasma citrato","Coagulométrico",                "s",       4,  "18.00"),
    ("TTPA",   "TTPa",                             "coagulacao", "plasma citrato","Coagulométrico",                "s",       4,  "18.00"),
    ("FIBRIN", "Fibrinogênio",                     "coagulacao", "plasma citrato","Clauss",                        "mg/dL",   4,  "20.00"),
    ("DDIMER", "D-dímero",                         "coagulacao", "plasma citrato","Turbidimetria",                 "ng/mL",   4,  "55.00"),
    ("AT_III", "Antitrombina III",                 "coagulacao", "plasma citrato","Cromogênico",                   "%",       24, "80.00"),
    ("PROT_C", "Proteína C",                       "coagulacao", "plasma citrato","Cromogênico",                   "%",       24, "80.00"),
    ("PROT_S", "Proteína S",                       "coagulacao", "plasma citrato","ELISA",                         "%",       48, "85.00"),
    ("FVIII",  "Fator VIII",                       "coagulacao", "plasma citrato","Coagulométrico",                "%",       48, "80.00"),
    ("FIX",    "Fator IX",                         "coagulacao", "plasma citrato","Coagulométrico",                "%",       48, "80.00"),

    # ==================== HORMÔNIOS ====================
    ("TSH",    "TSH",                              "hormonios", "soro",           "Quimiluminescência",            "µUI/mL",  24, "45.00"),
    ("T4L",    "T4 livre",                         "hormonios", "soro",           "Quimiluminescência",            "ng/dL",   24, "45.00"),
    ("T3L",    "T3 livre",                         "hormonios", "soro",           "Quimiluminescência",            "pg/mL",   24, "50.00"),
    ("T4T",    "T4 total",                         "hormonios", "soro",           "Quimiluminescência",            "µg/dL",   24, "35.00"),
    ("T3T",    "T3 total",                         "hormonios", "soro",           "Quimiluminescência",            "ng/dL",   24, "35.00"),
    ("TG",     "Tireoglobulina",                   "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   48, "70.00"),
    ("ATG",    "Anti-tireoglobulina",              "hormonios", "soro",           "Quimiluminescência",            "UI/mL",   48, "55.00"),
    ("ATPO",   "Anti-TPO",                         "hormonios", "soro",           "Quimiluminescência",            "UI/mL",   48, "55.00"),
    ("TRAB",   "TRAb",                             "hormonios", "soro",           "Radioimunoensaio",              "UI/L",    72, "90.00"),
    ("CALCIT", "Calcitonina",                      "hormonios", "soro",           "Quimiluminescência",            "pg/mL",   48, "85.00"),
    ("PTH",    "Paratormônio (PTH intacto)",       "hormonios", "soro",           "Quimiluminescência",            "pg/mL",   24, "70.00"),
    ("VITD",   "Vitamina D (25-OH)",               "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   48, "80.00"),
    ("VITB12", "Vitamina B12",                     "hormonios", "soro",           "Quimiluminescência",            "pg/mL",   24, "60.00"),
    ("FOLATO", "Ácido fólico",                     "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   24, "60.00"),
    ("FERRIT", "Ferritina",                        "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   24, "55.00"),
    ("INS",    "Insulina",                         "hormonios", "soro",           "Quimiluminescência",            "µUI/mL",  24, "55.00"),
    ("HOMA",   "HOMA-IR",                          "hormonios", "soro",           "Cálculo",                       None,      24, "20.00"),
    ("CORT",   "Cortisol",                         "hormonios", "soro",           "Quimiluminescência",            "µg/dL",   24, "45.00"),
    ("ACTH",   "ACTH",                             "hormonios", "plasma EDTA",    "Quimiluminescência",            "pg/mL",   48, "70.00"),
    ("PROG",   "Progesterona",                     "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   24, "45.00"),
    ("EST",    "Estradiol",                        "hormonios", "soro",           "Quimiluminescência",            "pg/mL",   24, "45.00"),
    ("TESTO",  "Testosterona total",               "hormonios", "soro",           "Quimiluminescência",            "ng/dL",   24, "50.00"),
    ("TESTOL", "Testosterona livre",               "hormonios", "soro",           "Quimiluminescência",            "pg/mL",   48, "70.00"),
    ("SHBG",   "SHBG",                             "hormonios", "soro",           "Quimiluminescência",            "nmol/L",  48, "70.00"),
    ("PRL",    "Prolactina",                       "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   24, "45.00"),
    ("FSH",    "FSH",                              "hormonios", "soro",           "Quimiluminescência",            "mUI/mL",  24, "45.00"),
    ("LH",     "LH",                               "hormonios", "soro",           "Quimiluminescência",            "mUI/mL",  24, "45.00"),
    ("HCG",    "Beta-HCG quantitativo",            "hormonios", "soro",           "Quimiluminescência",            "mUI/mL",  4,  "55.00"),
    ("PSA",    "PSA total",                        "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   24, "55.00"),
    ("PSAL",   "PSA livre",                        "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   24, "55.00"),
    ("HGH",    "Hormônio do crescimento (GH)",     "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   48, "65.00"),
    ("IGF1",   "IGF-1",                            "hormonios", "soro",           "Quimiluminescência",            "ng/mL",   48, "80.00"),
    ("ALDO",   "Aldosterona",                      "hormonios", "soro",           "Quimiluminescência",            "ng/dL",   48, "85.00"),
    ("REN",    "Renina",                           "hormonios", "plasma EDTA",    "Quimiluminescência",            "µUI/mL",  48, "85.00"),

    # ==================== IMUNOLOGIA ====================
    ("VDRL",   "VDRL",                             "imunologia", "soro",          "Floculação",                    None,      24, "25.00"),
    ("FTA",    "FTA-ABS IgG",                      "imunologia", "soro",          "Imunofluorescência",            None,      48, "45.00"),
    ("HIV",    "Anti-HIV 1/2",                     "imunologia", "soro",          "Quimiluminescência",            None,      24, "45.00"),
    ("HBSAG",  "HBsAg",                            "imunologia", "soro",          "Quimiluminescência",            None,      24, "35.00"),
    ("ANTIHBS","Anti-HBs",                         "imunologia", "soro",          "Quimiluminescência",            "UI/L",    24, "40.00"),
    ("ANTIHBC","Anti-HBc total",                   "imunologia", "soro",          "Quimiluminescência",            None,      24, "40.00"),
    ("HBCIGM", "Anti-HBc IgM",                     "imunologia", "soro",          "Quimiluminescência",            None,      24, "45.00"),
    ("HCV",    "Anti-HCV",                         "imunologia", "soro",          "Quimiluminescência",            None,      24, "50.00"),
    ("HAV_G",  "Anti-HAV IgG",                     "imunologia", "soro",          "Quimiluminescência",            None,      48, "45.00"),
    ("HAV_M",  "Anti-HAV IgM",                     "imunologia", "soro",          "Quimiluminescência",            None,      48, "50.00"),
    ("TOXO_G", "Toxoplasmose IgG",                 "imunologia", "soro",          "Quimiluminescência",            "UI/mL",   24, "45.00"),
    ("TOXO_M", "Toxoplasmose IgM",                 "imunologia", "soro",          "Quimiluminescência",            None,      24, "50.00"),
    ("CMV_G",  "Citomegalovírus IgG",              "imunologia", "soro",          "Quimiluminescência",            "UA/mL",   24, "50.00"),
    ("CMV_M",  "Citomegalovírus IgM",              "imunologia", "soro",          "Quimiluminescência",            None,      24, "50.00"),
    ("RUB_G",  "Rubéola IgG",                      "imunologia", "soro",          "Quimiluminescência",            "UI/mL",   24, "45.00"),
    ("RUB_M",  "Rubéola IgM",                      "imunologia", "soro",          "Quimiluminescência",            None,      24, "50.00"),
    ("EBV_G",  "Epstein-Barr IgG",                 "imunologia", "soro",          "ELISA",                         None,      48, "55.00"),
    ("HSV_G",  "Herpes simplex IgG",               "imunologia", "soro",          "Quimiluminescência",            None,      48, "55.00"),
    ("DENGUE", "Dengue IgG/IgM/NS1",               "imunologia", "soro",          "Imunocromatografia",            None,      4,  "60.00"),
    ("CHIKV",  "Chikungunya IgM",                  "imunologia", "soro",          "ELISA",                         None,      48, "80.00"),
    ("ZIKA",   "Zika IgM",                         "imunologia", "soro",          "ELISA",                         None,      48, "90.00"),
    ("FAN",    "FAN (ANA)",                        "imunologia", "soro",          "Imunofluorescência",            None,      48, "55.00"),
    ("ADNA",   "Anti-DNA nativo",                  "imunologia", "soro",          "Crithidia luciliae",            None,      48, "65.00"),
    ("ASM",    "Anti-músculo liso",                "imunologia", "soro",          "IFI",                           None,      48, "55.00"),
    ("AMA",    "Anti-mitocôndria",                 "imunologia", "soro",          "IFI",                           None,      48, "55.00"),
    ("ANCA",   "ANCA (c/p)",                       "imunologia", "soro",          "IFI",                           None,      48, "70.00"),
    ("FR",     "Fator reumatoide",                 "imunologia", "soro",          "Nefelometria",                  "UI/mL",   4,  "22.00"),
    ("ASO",    "ASO (Antiestreptolisina O)",       "imunologia", "soro",          "Nefelometria",                  "UI/mL",   4,  "22.00"),
    ("IGG",    "Imunoglobulina G",                 "imunologia", "soro",          "Nefelometria",                  "mg/dL",   24, "35.00"),
    ("IGA",    "Imunoglobulina A",                 "imunologia", "soro",          "Nefelometria",                  "mg/dL",   24, "35.00"),
    ("IGM",    "Imunoglobulina M",                 "imunologia", "soro",          "Nefelometria",                  "mg/dL",   24, "35.00"),
    ("IGE",    "Imunoglobulina E total",           "imunologia", "soro",          "Quimiluminescência",            "UI/mL",   24, "45.00"),
    ("C3",     "Complemento C3",                   "imunologia", "soro",          "Nefelometria",                  "mg/dL",   24, "35.00"),
    ("C4",     "Complemento C4",                   "imunologia", "soro",          "Nefelometria",                  "mg/dL",   24, "35.00"),
    ("CEA",    "CEA (antígeno carcinoembriônico)", "imunologia", "soro",          "Quimiluminescência",            "ng/mL",   24, "55.00"),
    ("CA125",  "CA 125",                           "imunologia", "soro",          "Quimiluminescência",            "U/mL",    24, "70.00"),
    ("CA153",  "CA 15-3",                          "imunologia", "soro",          "Quimiluminescência",            "U/mL",    24, "70.00"),
    ("CA199",  "CA 19-9",                          "imunologia", "soro",          "Quimiluminescência",            "U/mL",    24, "70.00"),
    ("AFP",    "Alfafetoproteína",                 "imunologia", "soro",          "Quimiluminescência",            "ng/mL",   24, "55.00"),

    # ==================== URINÁLISE ====================
    ("URI",    "EAS / Urina rotina",               "urinalise", "urina",          "Fita reagente + microscopia",    None,     4,  "20.00"),
    ("URC",    "Urocultura",                       "urinalise", "urina",          "Ágar CLED / MacConkey",         None,      72, "35.00"),
    ("CIT_URI","Citologia urinária",               "urinalise", "urina",          "Papanicolaou",                  None,      72, "45.00"),
    ("BENCE",  "Proteína de Bence-Jones",          "urinalise", "urina",          "Eletroforese",                  None,      48, "55.00"),

    # ==================== PARASITOLOGIA ====================
    ("PARA",   "Parasitológico de fezes",          "parasitologia", "fezes",       "Hoffman + Faust",              None,      48, "22.00"),
    ("PARA_3", "Parasitológico (3 amostras)",      "parasitologia", "fezes",       "Hoffman + Faust",              None,      48, "50.00"),
    ("SANG_OC","Pesquisa de sangue oculto",        "parasitologia", "fezes",       "Imunocromatografia",           None,      24, "25.00"),
    ("ROTA",   "Rotavírus (fezes)",                "parasitologia", "fezes",       "Imunocromatografia",           None,      24, "40.00"),
    ("GIA_AG", "Giardia antígeno",                 "parasitologia", "fezes",       "ELISA",                        None,      48, "35.00"),
    ("CRIP",   "Criptosporidium (pesquisa)",       "parasitologia", "fezes",       "Ziehl-Neelsen modificado",     None,      48, "40.00"),
    ("COPRO",  "Coprocultura",                     "parasitologia", "fezes",       "Ágar SS / MacConkey",          None,      72, "40.00"),

    # ==================== MICROBIOLOGIA ====================
    ("HEMO_C", "Hemocultura (aeróbio)",            "microbiologia", "sangue",     "BacT/ALERT",                    None,      120,"55.00"),
    ("HEMO_A", "Hemocultura (anaeróbio)",          "microbiologia", "sangue",     "BacT/ALERT",                    None,      120,"55.00"),
    ("CULT_S", "Cultura secreção geral",           "microbiologia", "secreção",   "Ágar sangue + MacConkey",       None,      72, "50.00"),
    ("BAAR",   "BAAR (baciloscopia TB)",           "microbiologia", "escarro",    "Ziehl-Neelsen",                 None,      24, "30.00"),
    ("MYCOB",  "Cultura de micobactéria",          "microbiologia", "escarro",    "Löwenstein-Jensen",             None,      1440,"80.00"),
    ("MICOSE", "Pesquisa micológica direta",       "microbiologia", "pele/unha",  "KOH + microscopia",             None,      48, "30.00"),
    ("MICOCULT","Cultura para fungos",             "microbiologia", "pele/unha",  "Sabouraud",                     None,      720,"55.00"),
    ("ATB",    "Antibiograma (por cultura)",       "microbiologia", "cultura",    "Disco-difusão / MIC",           None,      48, "40.00"),

    # ==================== GASOMETRIA & OUTROS ====================
    ("GAS_A",  "Gasometria arterial",              "gasometria", "sangue arterial","ISE + potenciometria",          None,      1,  "40.00"),
    ("GAS_V",  "Gasometria venosa",                "gasometria", "sangue venoso", "ISE + potenciometria",          None,      1,  "35.00"),
    ("LACT",   "Lactato",                          "gasometria", "sangue arterial","Enzimático",                    "mmol/L",  1,  "25.00"),
    ("AM",     "Amônia",                           "gasometria", "plasma EDTA",    "Enzimático UV",                 "µg/dL",   4,  "35.00"),

    # ==================== FARMACOLOGIA / TÓXICOS ====================
    ("LITHIUM","Lítio",                            "farmacologia", "soro",         "Fotometria de chama",           "mEq/L",   6,  "35.00"),
    ("DIGOX",  "Digoxina",                         "farmacologia", "soro",         "Quimiluminescência",            "ng/mL",   24, "60.00"),
    ("VALP",   "Valproato",                        "farmacologia", "soro",         "Imunoensaio",                   "µg/mL",   24, "60.00"),
    ("CARBM",  "Carbamazepina",                    "farmacologia", "soro",         "Imunoensaio",                   "µg/mL",   24, "60.00"),
    ("FENOB",  "Fenobarbital",                     "farmacologia", "soro",         "Imunoensaio",                   "µg/mL",   24, "60.00"),
    ("FENIT",  "Fenitoína",                        "farmacologia", "soro",         "Imunoensaio",                   "µg/mL",   24, "60.00"),
    ("TACRO",  "Tacrolimo",                        "farmacologia", "sangue EDTA",  "Quimiluminescência",            "ng/mL",   24, "120.00"),
    ("CICLOS", "Ciclosporina",                     "farmacologia", "sangue EDTA",  "Quimiluminescência",            "ng/mL",   24, "120.00"),
    ("METOTX", "Metotrexato",                      "farmacologia", "soro",         "Imunoensaio",                   "µmol/L",  24, "80.00"),
    ("VANC",   "Vancomicina",                      "farmacologia", "soro",         "Imunoensaio",                   "µg/mL",   6,  "55.00"),
    ("GENT",   "Gentamicina",                      "farmacologia", "soro",         "Imunoensaio",                   "µg/mL",   6,  "55.00"),

    # ==================== MARCADORES CARDÍACOS ====================
    ("TROPI",  "Troponina I ultra-sensível",       "cardiacos", "soro",            "Quimiluminescência",            "pg/mL",   1,  "80.00"),
    ("TROPT",  "Troponina T ultra-sensível",       "cardiacos", "soro",            "Quimiluminescência",            "ng/L",    1,  "80.00"),
    ("BNP",    "BNP",                              "cardiacos", "plasma EDTA",     "Quimiluminescência",            "pg/mL",   4,  "90.00"),
    ("NTPRO",  "NT-proBNP",                        "cardiacos", "plasma EDTA",     "Quimiluminescência",            "pg/mL",   4,  "90.00"),
    ("MIOGLB", "Mioglobina",                       "cardiacos", "soro",            "Quimiluminescência",            "ng/mL",   2,  "55.00"),

    # ==================== ALERGIA / ESPECIAIS ====================
    ("HOMOC",  "Homocisteína",                     "especiais", "plasma EDTA",     "Quimiluminescência",            "µmol/L",  48, "80.00"),
    ("APO_A",  "Apolipoproteína A1",               "especiais", "soro",            "Imunoturbidimetria",            "mg/dL",   24, "55.00"),
    ("APO_B",  "Apolipoproteína B",                "especiais", "soro",            "Imunoturbidimetria",            "mg/dL",   24, "55.00"),
    ("LIPO_A", "Lipoproteína (a)",                 "especiais", "soro",            "Imunoturbidimetria",            "mg/dL",   24, "60.00"),
    ("ANTI_A", "Anticorpo A/B",                    "especiais", "soro",            "Aglutinação",                   None,      24, "25.00"),
    ("ABO_RH", "Grupo sanguíneo + Rh",             "hematologia", "sangue EDTA",   "Aglutinação",                   None,      2,  "18.00"),
    ("TIP_SANG","Tipagem sanguínea completa",      "hematologia", "sangue EDTA",   "Aglutinação em gel",            None,      4,  "35.00"),
]
